FROM golang:1.9.2

COPY ./pluksrv.go "$GOPATH/src/github.com/kuberlab/pluk/pluksrv.go"
COPY ./pkg "$GOPATH/src/github.com/kuberlab/pluk/pkg"
COPY ./cmd "$GOPATH/src/github.com/kuberlab/pluk/cmd"
COPY ./vendor "$GOPATH/src/github.com/kuberlab/pluk/vendor"

RUN cd "$GOPATH/src/github.com/kuberlab/pluk" && go build ./cmd/plukefs/

FROM ubuntu:16.04

COPY --from=0 /go/src/github.com/kuberlab/pluk/plukefs /usr/bin/plukefs
RUN apt-get update
RUN apt-get install -y libfuse-dev fuse

