// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/pluke.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing chunk request path and auth.
type ChunkRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Auth                 *Auth    `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChunkRequest) Reset()         { *m = ChunkRequest{} }
func (m *ChunkRequest) String() string { return proto.CompactTextString(m) }
func (*ChunkRequest) ProtoMessage()    {}
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff1b29b4d606917, []int{0}
}

func (m *ChunkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkRequest.Unmarshal(m, b)
}
func (m *ChunkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkRequest.Marshal(b, m, deterministic)
}
func (m *ChunkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkRequest.Merge(m, src)
}
func (m *ChunkRequest) XXX_Size() int {
	return xxx_messageInfo_ChunkRequest.Size(m)
}
func (m *ChunkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkRequest proto.InternalMessageInfo

func (m *ChunkRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ChunkRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ChunkRequest) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

// The request message containing chunk request path and auth.
type ChunkRequestWithCheck struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Auth                 *Auth    `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChunkRequestWithCheck) Reset()         { *m = ChunkRequestWithCheck{} }
func (m *ChunkRequestWithCheck) String() string { return proto.CompactTextString(m) }
func (*ChunkRequestWithCheck) ProtoMessage()    {}
func (*ChunkRequestWithCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff1b29b4d606917, []int{1}
}

func (m *ChunkRequestWithCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkRequestWithCheck.Unmarshal(m, b)
}
func (m *ChunkRequestWithCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkRequestWithCheck.Marshal(b, m, deterministic)
}
func (m *ChunkRequestWithCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkRequestWithCheck.Merge(m, src)
}
func (m *ChunkRequestWithCheck) XXX_Size() int {
	return xxx_messageInfo_ChunkRequestWithCheck.Size(m)
}
func (m *ChunkRequestWithCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkRequestWithCheck.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkRequestWithCheck proto.InternalMessageInfo

func (m *ChunkRequestWithCheck) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ChunkRequestWithCheck) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ChunkRequestWithCheck) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ChunkRequestWithCheck) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

// The response message containing the chunk data
type ChunkResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChunkResponse) Reset()         { *m = ChunkResponse{} }
func (m *ChunkResponse) String() string { return proto.CompactTextString(m) }
func (*ChunkResponse) ProtoMessage()    {}
func (*ChunkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff1b29b4d606917, []int{2}
}

func (m *ChunkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkResponse.Unmarshal(m, b)
}
func (m *ChunkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkResponse.Marshal(b, m, deterministic)
}
func (m *ChunkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkResponse.Merge(m, src)
}
func (m *ChunkResponse) XXX_Size() int {
	return xxx_messageInfo_ChunkResponse.Size(m)
}
func (m *ChunkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkResponse proto.InternalMessageInfo

func (m *ChunkResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Auth struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Workspace            string   `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Secret               string   `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_dff1b29b4d606917, []int{3}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Auth) GetWorkspace() string {
	if m != nil {
		return m.Workspace
	}
	return ""
}

func (m *Auth) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func init() {
	proto.RegisterType((*ChunkRequest)(nil), "grpc.ChunkRequest")
	proto.RegisterType((*ChunkRequestWithCheck)(nil), "grpc.ChunkRequestWithCheck")
	proto.RegisterType((*ChunkResponse)(nil), "grpc.ChunkResponse")
	proto.RegisterType((*Auth)(nil), "grpc.Auth")
}

func init() { proto.RegisterFile("protos/pluke.proto", fileDescriptor_dff1b29b4d606917) }

var fileDescriptor_dff1b29b4d606917 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcb, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0xff, 0xfc, 0x4d, 0x0b, 0x99, 0x16, 0x09, 0x86, 0x8b, 0x22, 0x40, 0xa8, 0x84, 0x4d,
	0x57, 0x41, 0x2a, 0xe2, 0x01, 0x68, 0x17, 0xdd, 0x56, 0x66, 0xc1, 0x86, 0x4d, 0x1a, 0x46, 0x38,
	0x72, 0x15, 0x1b, 0x5f, 0x8a, 0xe0, 0x05, 0x78, 0x6d, 0x64, 0x37, 0xbd, 0x20, 0xd4, 0x05, 0xbb,
	0x39, 0x63, 0xcd, 0x39, 0x9f, 0xc6, 0x03, 0xa8, 0xb4, 0xb4, 0xd2, 0xdc, 0xaa, 0xb9, 0x13, 0x94,
	0x07, 0x81, 0xf1, 0xab, 0x56, 0x65, 0xf6, 0x0c, 0xbd, 0x31, 0x77, 0xb5, 0x60, 0xf4, 0xe6, 0xc8,
	0x58, 0x44, 0x88, 0x55, 0x61, 0x79, 0x1a, 0xf5, 0xa3, 0x41, 0xc2, 0x42, 0x8d, 0x29, 0xec, 0x2d,
	0x48, 0x9b, 0x4a, 0xd6, 0xe9, 0xff, 0x7e, 0x34, 0x68, 0xb3, 0x95, 0xc4, 0x2b, 0x88, 0x0b, 0x67,
	0x79, 0xda, 0xea, 0x47, 0x83, 0xee, 0x10, 0x72, 0x6f, 0x99, 0x3f, 0x38, 0xcb, 0x59, 0xe8, 0x67,
	0x1f, 0x70, 0xba, 0xed, 0xfe, 0x54, 0x59, 0x3e, 0xe6, 0x54, 0x8a, 0x3f, 0xc6, 0x20, 0xc4, 0xa6,
	0xfa, 0xa4, 0x10, 0xd3, 0x62, 0xa1, 0x5e, 0x47, 0xc7, 0x3b, 0xa2, 0x6f, 0xe0, 0xa0, 0x89, 0x36,
	0x4a, 0xd6, 0x86, 0xbc, 0xc9, 0x4b, 0x61, 0x8b, 0x10, 0xd9, 0x63, 0xa1, 0xce, 0x18, 0xc4, 0x7e,
	0x04, 0x4f, 0xa0, 0x6d, 0xa5, 0xa0, 0xba, 0xe1, 0x59, 0x0a, 0xbc, 0x84, 0xe4, 0x5d, 0x6a, 0x61,
	0x54, 0x51, 0x52, 0x40, 0x4a, 0xd8, 0xa6, 0x81, 0x67, 0xd0, 0x31, 0x54, 0x6a, 0xb2, 0x01, 0x2b,
	0x61, 0x8d, 0x1a, 0x7e, 0x45, 0xd0, 0x9e, 0xfa, 0x3d, 0xe3, 0x3d, 0xec, 0x4f, 0xc8, 0x06, 0x0a,
	0xc4, 0x25, 0xe0, 0xf6, 0x36, 0xce, 0x8f, 0x7f, 0xf4, 0x96, 0x98, 0xd9, 0x3f, 0x9c, 0xc0, 0xd1,
	0x6a, 0x6c, 0xb3, 0xb0, 0x8b, 0xdf, 0xf3, 0xeb, 0xc7, 0x1d, 0x46, 0xa3, 0x6b, 0x38, 0xac, 0x64,
	0x2e, 0xdc, 0x8c, 0xf4, 0xbc, 0x98, 0xe5, 0xfe, 0xf3, 0x47, 0xdd, 0x47, 0xd2, 0x0b, 0xd2, 0x53,
	0x7f, 0x02, 0xd3, 0x68, 0xd6, 0x09, 0xb7, 0x70, 0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xdc,
	0x1a, 0xde, 0x21, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlukeClient is the client API for Pluke service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlukeClient interface {
	// Obtains the chunk at given path.
	GetChunk(ctx context.Context, in *ChunkRequest, opts ...grpc.CallOption) (*ChunkResponse, error)
	GetChunkWithCheck(ctx context.Context, in *ChunkRequestWithCheck, opts ...grpc.CallOption) (*ChunkResponse, error)
}

type plukeClient struct {
	cc *grpc.ClientConn
}

func NewPlukeClient(cc *grpc.ClientConn) PlukeClient {
	return &plukeClient{cc}
}

func (c *plukeClient) GetChunk(ctx context.Context, in *ChunkRequest, opts ...grpc.CallOption) (*ChunkResponse, error) {
	out := new(ChunkResponse)
	err := c.cc.Invoke(ctx, "/grpc.Pluke/GetChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plukeClient) GetChunkWithCheck(ctx context.Context, in *ChunkRequestWithCheck, opts ...grpc.CallOption) (*ChunkResponse, error) {
	out := new(ChunkResponse)
	err := c.cc.Invoke(ctx, "/grpc.Pluke/GetChunkWithCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlukeServer is the server API for Pluke service.
type PlukeServer interface {
	// Obtains the chunk at given path.
	GetChunk(context.Context, *ChunkRequest) (*ChunkResponse, error)
	GetChunkWithCheck(context.Context, *ChunkRequestWithCheck) (*ChunkResponse, error)
}

// UnimplementedPlukeServer can be embedded to have forward compatible implementations.
type UnimplementedPlukeServer struct {
}

func (*UnimplementedPlukeServer) GetChunk(ctx context.Context, req *ChunkRequest) (*ChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChunk not implemented")
}
func (*UnimplementedPlukeServer) GetChunkWithCheck(ctx context.Context, req *ChunkRequestWithCheck) (*ChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChunkWithCheck not implemented")
}

func RegisterPlukeServer(s *grpc.Server, srv PlukeServer) {
	s.RegisterService(&_Pluke_serviceDesc, srv)
}

func _Pluke_GetChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlukeServer).GetChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Pluke/GetChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlukeServer).GetChunk(ctx, req.(*ChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pluke_GetChunkWithCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkRequestWithCheck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlukeServer).GetChunkWithCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Pluke/GetChunkWithCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlukeServer).GetChunkWithCheck(ctx, req.(*ChunkRequestWithCheck))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pluke_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Pluke",
	HandlerType: (*PlukeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChunk",
			Handler:    _Pluke_GetChunk_Handler,
		},
		{
			MethodName: "GetChunkWithCheck",
			Handler:    _Pluke_GetChunkWithCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/pluke.proto",
}
